import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  metadataBase: new URL('https://zijinzhangprofile.com'),
  title: {
    default: "Zijin Zhang | AI Product Builder & Banking Specialist",
    template: "%s | Zijin Zhang"
  },
  description: "I build AI-powered products and deliver excellent customer experiences. Founder of VectorPaths, an adaptive learning platform. Experienced in AI/LLM engineering, product strategy, and banking operations at Commonwealth Bank.",
  keywords: ["Zijin Zhang", "AI Product Manager", "Product Builder", "Machine Learning", "LLM Engineering", "Banking Specialist", "Melbourne", "Australia", "VectorPaths", "Adaptive Learning", "Data-Driven Product", "AI Strategy", "Product Roadmap", "User Experience", "Commonwealth Bank"],
  authors: [{ name: "Zijin Zhang", url: "https://zijinzhangprofile.com" }],
  creator: "Zijin Zhang",
  openGraph: {
    title: "Zijin Zhang | AI Product Builder & Banking Specialist",
    description: "I build AI-powered products and deliver excellent customer experiences. Founder of VectorPaths. Banking specialist at Commonwealth Bank.",
    url: "https://zijinzhangprofile.com",
    siteName: "Zijin Zhang Portfolio",
    locale: "en_AU",
    type: "website",
    // OG image is auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Zijin Zhang | AI Product Builder & Banking Specialist",
    description: "I build AI-powered products and deliver excellent customer experiences. Founder of VectorPaths. Banking specialist at Commonwealth Bank.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'b9DfI0xgdtWZKSKJhwgZJ9Vhg-_cudWl7NOMsz4FkSo',
  },
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Zijin Zhang',
  url: 'https://zijinzhangprofile.com',
  jobTitle: 'AI Product Builder & Banking Specialist',
  description: 'I build AI-powered products and deliver excellent customer experiences. Founder of VectorPaths, an adaptive learning platform.',
  knowsAbout: ['AI Product Management', 'Machine Learning', 'LLM Engineering', 'Product Strategy', 'Data Analysis', 'User Experience', 'Adaptive Learning Systems', 'Banking Operations', 'Agile Development'],
  alumniOf: {
    '@type': 'CollegeOrUniversity',
    name: 'University of Melbourne'
  },
  worksFor: {
    '@type': 'Organization',
    name: 'Commonwealth Bank of Australia'
  },
  sameAs: [
    'https://www.linkedin.com/in/zijin-zhang-2578b92b1',
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-AU">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className={`${inter.variable} font-sans antialiased bg-cream`}>
        <Navigation />
        <main id="main-content">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
